---
- hosts: localhost
  tasks:
  - name: Create security group for node communication
    amazon.aws.ec2_security_group:
      name: flume-sg
      description: sg with total access within flume nodes
      region: us-east-1
      rules:
        - proto: all
          group_name: flume-sg
        - proto: all
          group_name: hadoop-sg
        - proto: tcp
          cidr_ip: 0.0.0.0/0
          ports: 
          - 22

  - name: Start flume source instances
    amazon.aws.ec2_instance:
      name: "flume-source-{{item}}"
      key_name: "vockey"
      instance_type: t2.micro
      security_group: 
        - flume-sg
        - hadoop-sg
      image_id: ami-051f7e7f6c2f40dc1
      region: us-east-1
      tags:
        Group: flume
      volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 10
          delete_on_termination: true
    loop:
      - "1"
      - "2"
      - "3" 

  - name: Start flume sink instance
    amazon.aws.ec2_instance:
      name: "flume-sink"
      key_name: "vockey"
      instance_type: t3.large
      security_group: 
        - flume-sg
        - hadoop-sg
      image_id: ami-051f7e7f6c2f40dc1
      region: us-east-1
      tags:
        Group: flume
      volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 50
          delete_on_termination: true