---
- hosts: localhost
  tasks:
  - name: Start flume source instances
    amazon.aws.ec2_instance:
      name: "flume-source-{{item}}"
      key_name: "vockey"
      instance_type: t3.small
      security_groups: 
        - hadoop-sg
      image_id: ami-051f7e7f6c2f40dc1
      region: us-east-1
      tags:
        Group: flume
      volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 8
          delete_on_termination: true
    loop:
      - "1"
      - "2"
      - "3"